" Baseline vimrc for automated testing suite.
" This file should not be edited when it isn't absolutely necessary.
"
" Copyright (C) 2021    Lucas Ritzdorf, Luca Zeuch
"
" This program is free software; you can redistribute it and/or modify
" it under the terms of the GNU General Public License as published by
" the Free Software Foundation; either version 2 of the License, or
" (at your option) any later version.
"
" This program is distributed in the hope that it will be useful,
" but WITHOUT ANY WARRANTY; without even the implied warranty of
" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
" GNU General Public License for more details.
"
" You should have received a copy of the GNU General Public License along
" with this program; if not, write to the Free Software Foundation, Inc.,
" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

" Set up the plugin and framework
set runtimepath+=../.bundle/vader.vim/
set runtimepath+=../

" Set up the required things for the plugin to run,
" also get rid of a few annoying things that would only
" pollute the user directory.
filetype plugin indent on
syntax enable
set nomore
set noswapfile
set viminfo=

set shiftwidth=2
set expandtab
