" Vim syntax file
" Add-on file, containing function keywords.
"
" Automatically generated. DO NOT EDIT.
"
" Copyright (C) 2024    Luca Zeuch, Lucas Ritzdorf
"
" This program is free software; you can redistribute it and/or modify
" it under the terms of the GNU General Public License as published by
" the Free Software Foundation; either version 2 of the License, or
" (at your option) any later version.
" This program is distributed in the hope that it will be useful,
" but WITHOUT ANY WARRANTY; without even the implied warranty of
" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
" GNU General Public License for more details.
"
" You should have received a copy of the GNU General Public License along
" with this program; if not, write to the Free Software Foundation, Inc.,
" 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

syn keyword yagFunc abs
syn keyword yagFunc add
syn keyword yagFunc addMessageReactions
syn keyword yagFunc addReactions
syn keyword yagFunc addResponseReactions
syn keyword yagFunc addRole
syn keyword yagFunc addRoleID
syn keyword yagFunc addRoleName
syn keyword yagFunc addThreadMember
syn keyword yagFunc adjective
syn keyword yagFunc and
syn keyword yagFunc bitwiseAnd
syn keyword yagFunc bitwiseAndNot
syn keyword yagFunc bitwiseLeftShift
syn keyword yagFunc bitwiseNot
syn keyword yagFunc bitwiseOr
syn keyword yagFunc bitwiseRightShift
syn keyword yagFunc bitwiseXor
syn keyword yagFunc call
syn keyword yagFunc cancelScheduledUniqueCC
syn keyword yagFunc carg
syn keyword yagFunc cbrt
syn keyword yagFunc cbutton
syn keyword yagFunc ccheckbox
syn keyword yagFunc ccheckboxGroup
syn keyword yagFunc cembed
syn keyword yagFunc clabel
syn keyword yagFunc closeThread
syn keyword yagFunc cmenu
syn keyword yagFunc cmodal
syn keyword yagFunc complexMessage
syn keyword yagFunc complexMessageEdit
syn keyword yagFunc componentBuilder
syn keyword yagFunc cradioGroup
syn keyword yagFunc createForumPost
syn keyword yagFunc createThread
syn keyword yagFunc createTicket
syn keyword yagFunc cslice
syn keyword yagFunc ctextDisplay
syn keyword yagFunc ctextInput
syn keyword yagFunc currentTime
syn keyword yagFunc currentUserAgeHuman
syn keyword yagFunc currentUserAgeMinutes
syn keyword yagFunc currentUserCreated
syn keyword yagFunc dbBottomEntries
syn keyword yagFunc dbCount
syn keyword yagFunc dbDel
syn keyword yagFunc dbDelByID
syn keyword yagFunc dbDelById
syn keyword yagFunc dbDelMultiple
syn keyword yagFunc dbGet
syn keyword yagFunc dbGetPattern
syn keyword yagFunc dbGetPatternReverse
syn keyword yagFunc dbIncr
syn keyword yagFunc dbRank
syn keyword yagFunc dbSet
syn keyword yagFunc dbSetExpire
syn keyword yagFunc dbTopEntries
syn keyword yagFunc decodeBase64
syn keyword yagFunc deleteAllMessageReactions
syn keyword yagFunc deleteForumPost
syn keyword yagFunc deleteInteractionResponse
syn keyword yagFunc deleteMessage
syn keyword yagFunc deleteMessageReaction
syn keyword yagFunc deleteResponse
syn keyword yagFunc deleteThread
syn keyword yagFunc deleteTrigger
syn keyword yagFunc dict
syn keyword yagFunc div
syn keyword yagFunc editChannelName
syn keyword yagFunc editChannelTopic
syn keyword yagFunc editComponentMessage
syn keyword yagFunc editComponentMessageNoEscape
syn keyword yagFunc editMessage
syn keyword yagFunc editMessageNoEscape
syn keyword yagFunc editNickname
syn keyword yagFunc editResponse
syn keyword yagFunc editResponseNoEscape
syn keyword yagFunc editThread
syn keyword yagFunc encodeBase64
syn keyword yagFunc ephemeralResponse
syn keyword yagFunc eq
syn keyword yagFunc exec
syn keyword yagFunc execAdmin
syn keyword yagFunc execCC
syn keyword yagFunc execTemplate
syn keyword yagFunc fdiv
syn keyword yagFunc formatTime
syn keyword yagFunc ge
syn keyword yagFunc getChannel
syn keyword yagFunc getChannelOrThread
syn keyword yagFunc getChannelPins
syn keyword yagFunc getMember
syn keyword yagFunc getMemberVoiceState
syn keyword yagFunc getMessage
syn keyword yagFunc getPinCount
syn keyword yagFunc getResponse
syn keyword yagFunc getRole
syn keyword yagFunc getRoleID
syn keyword yagFunc getRoleName
syn keyword yagFunc getTargetPermissionsIn
syn keyword yagFunc getThread
syn keyword yagFunc giveRole
syn keyword yagFunc giveRoleID
syn keyword yagFunc giveRoleName
syn keyword yagFunc gt
syn keyword yagFunc hasAnyPermissions
syn keyword yagFunc hasPermissions
syn keyword yagFunc hasPrefix
syn keyword yagFunc hasRole
syn keyword yagFunc hasRoleID
syn keyword yagFunc hasRoleName
syn keyword yagFunc hasSuffix
syn keyword yagFunc hash
syn keyword yagFunc html
syn keyword yagFunc humanizeDurationHours
syn keyword yagFunc humanizeDurationMinutes
syn keyword yagFunc humanizeDurationSeconds
syn keyword yagFunc humanizeThousands
syn keyword yagFunc humanizeTimeSinceDays
syn keyword yagFunc in
syn keyword yagFunc inFold
syn keyword yagFunc index
syn keyword yagFunc joinStr
syn keyword yagFunc js
syn keyword yagFunc json
syn keyword yagFunc jsonToSdict
syn keyword yagFunc kindOf
syn keyword yagFunc le
syn keyword yagFunc len
syn keyword yagFunc loadLocation
syn keyword yagFunc log
syn keyword yagFunc lower
syn keyword yagFunc lt
syn keyword yagFunc mathConst
syn keyword yagFunc max
syn keyword yagFunc memberAbove
syn keyword yagFunc memberAboveRole
syn keyword yagFunc mentionEveryone
syn keyword yagFunc mentionHere
syn keyword yagFunc mentionRole
syn keyword yagFunc mentionRoleID
syn keyword yagFunc mentionRoleName
syn keyword yagFunc min
syn keyword yagFunc mod
syn keyword yagFunc modalBuilder
syn keyword yagFunc mult
syn keyword yagFunc ne
syn keyword yagFunc newDate
syn keyword yagFunc not
syn keyword yagFunc noun
syn keyword yagFunc onlineCount
syn keyword yagFunc onlineCountBots
syn keyword yagFunc openThread
syn keyword yagFunc or
syn keyword yagFunc parseArgs
syn keyword yagFunc parseTime
syn keyword yagFunc pastNicknames
syn keyword yagFunc pastUsernames
syn keyword yagFunc pinForumPost
syn keyword yagFunc pinMessage
syn keyword yagFunc pow
syn keyword yagFunc print
syn keyword yagFunc printf
syn keyword yagFunc println
syn keyword yagFunc publishMessage
syn keyword yagFunc publishResponse
syn keyword yagFunc randInt
syn keyword yagFunc reFind
syn keyword yagFunc reFindAll
syn keyword yagFunc reFindAllSubmatches
syn keyword yagFunc reQuoteMeta
syn keyword yagFunc reReplace
syn keyword yagFunc reSplit
syn keyword yagFunc removeRole
syn keyword yagFunc removeRoleID
syn keyword yagFunc removeRoleName
syn keyword yagFunc removeThreadMember
syn keyword yagFunc roleAbove
syn keyword yagFunc round
syn keyword yagFunc roundCeil
syn keyword yagFunc roundEven
syn keyword yagFunc roundFloor
syn keyword yagFunc sanitizeText
syn keyword yagFunc scheduleUniqueCC
syn keyword yagFunc sdict
syn keyword yagFunc sendComponentMessage
syn keyword yagFunc sendComponentMessageNoEscape
syn keyword yagFunc sendComponentMessageNoEscapeRetID
syn keyword yagFunc sendComponentMessageRetID
syn keyword yagFunc sendDM
syn keyword yagFunc sendMessage
syn keyword yagFunc sendMessageNoEscape
syn keyword yagFunc sendMessageNoEscapeRetID
syn keyword yagFunc sendMessageRetID
syn keyword yagFunc sendModal
syn keyword yagFunc sendResponse
syn keyword yagFunc sendResponseNoEscape
syn keyword yagFunc sendResponseNoEscapeRetID
syn keyword yagFunc sendResponseRetID
syn keyword yagFunc sendTemplate
syn keyword yagFunc sendTemplateDM
syn keyword yagFunc seq
syn keyword yagFunc setRoles
syn keyword yagFunc shuffle
syn keyword yagFunc sleep
syn keyword yagFunc slice
syn keyword yagFunc snowflakeToTime
syn keyword yagFunc sort
syn keyword yagFunc split
syn keyword yagFunc sqrt
syn keyword yagFunc str
syn keyword yagFunc structToSdict
syn keyword yagFunc sub
syn keyword yagFunc takeRole
syn keyword yagFunc takeRoleID
syn keyword yagFunc takeRoleName
syn keyword yagFunc targetHasAnyPermissions
syn keyword yagFunc targetHasPermissions
syn keyword yagFunc targetHasRole
syn keyword yagFunc targetHasRoleID
syn keyword yagFunc targetHasRoleName
syn keyword yagFunc timestampToTime
syn keyword yagFunc title
syn keyword yagFunc toByte
syn keyword yagFunc toDuration
syn keyword yagFunc toFloat
syn keyword yagFunc toInt
syn keyword yagFunc toInt64
syn keyword yagFunc toRune
syn keyword yagFunc toString
syn keyword yagFunc trimSpace
syn keyword yagFunc unpinForumPost
syn keyword yagFunc unpinMessage
syn keyword yagFunc updateMessage
syn keyword yagFunc updateMessageNoEscape
syn keyword yagFunc upper
syn keyword yagFunc urlescape
syn keyword yagFunc urlquery
syn keyword yagFunc urlunescape
syn keyword yagFunc userArg
syn keyword yagFunc verb
syn keyword yagFunc weekNumber
hi def link yagFunc Function
